spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/?currentSchema=users
    username: abarrena0
    password: abarrena0_tfg
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:19092
mybatis:
  configuration:
    map-underscore-to-camel-case: true
jwt:
  secret: abarrena0_uoc_edu
  expiration: 86400000
server:
  port: 8082
application:
  name: users-service
  version: 1.0.0
  defaultLanguage: en_US