CREATE SCHEMA IF NOT EXISTS USERS;

SET SEARCH_PATH = 'USERS';

CREATE TABLE IF NOT EXISTS APP_USER (
	ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	ROLE VARCHAR(20) NOT NULL CHECK (ROLE IN ('TRAVELER', 'COMPANY', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS TRAVELER (
) INHERITS (APP_USER);

CREATE TABLE IF NOT EXISTS COMPANY (
	CIF VARCHAR(9) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(255) NOT NULL,
	DESCRIPTION TEXT,
	PHONE VARCHAR(9),
	EMAIL VARCHAR(50)
) INHERITS (APP_USER);

CREATE TABLE IF NOT EXISTS DIVE_DIARY (
  ID SERIAL PRIMARY KEY,
  DATE DATE NOT NULL,
  TIME TIME NOT NULL,
  SPOT VARCHAR(50) NOT NULL,
  MAX_DEPTH DOUBLE PRECISION,
  TEMPERATURE DOUBLE PRECISION,
  VISIBILITY INTEGER,
  O2_PERCENTAGE INTEGER,
  AIR_IN INTEGER,
  AIR_OUT INTEGER,
  COMMENT TEXT,
  TRAVELER_ID BIGINT
);

ALTER TABLE DIVE_DIARY ADD CONSTRAINT FK_DIVE_DIARY_TRAVELER FOREIGN KEY (TRAVELER_ID) REFERENCES APP_USER(ID);