CREATE SCHEMA IF NOT EXISTS USERS;

set search_path = 'users';

CREATE TABLE IF NOT EXISTS APP_USER (
	ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	ROLE VARCHAR(20) NOT NULL CHECK (ROLE IN ('TRAVELER', 'COMPANY', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS TRAVELER (
) INHERITS (APP_USER);

CREATE TABLE IF NOT EXISTS COMPANY (
	CIF VARCHAR(9) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(5000),
	PHONE VARCHAR(9),
	EMAIL VARCHAR(50)
) INHERITS (APP_USER);